version: 2.1

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Run Docker container
          command: |
            docker run -v echo.sh:/semantic-tests -d --name plexil-container semantictests/semantictests:plexil-image tail -f /dev/null
      - run:
          name: Run commands inside container
          command: |
            docker exec plexil-container ./plexil/test/TestExec-regression-test/run-tests
            docker exec plexil-container sh -c ./semantic-tests/echo.sh

workflows:
  version: 2
  build:
    jobs:
      - build