version: 2.1

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t plexil-image .
      - run:
          name: Run Docker container
          command: |
            docker run -it -d --name plexil-container plexil-image bash
            ./plexil/test/TestExec-regression-test/run-tests
            cd /semantic-tests
workflows:
  version: 2
  build:
    jobs:
      - build