version: 2.1

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker pull semantictests/semantictests:plexil-image
      - run:
          name: Run Docker container
          command: |
            docker run -d --name plexil-container plexil-image tail -f /dev/null
      - run:
          name: Run commands inside container
          command: |
            docker exec plexil-container ./plexil/test/TestExec-regression-test/run-tests
            docker exec plexil-container sh -c "cd semantic-tests"

workflows:
  version: 2
  build:
    jobs:
      - build