version: 2.1

jobs:
  build:
    docker:
      - image: semantictests/semantictests:plexil-image
        volumes:
          - README.md:/
    working_directory: /
    steps:
      - run:
          name: Execute tests
          command: |
            ./plexil/test/TestExec-regression-test/run-tests

workflows:
  version: 2
  build:
    jobs:
      - build
