version: 2.1

jobs:
  build:
    docker:
      - image: semantictests/semantictests:plexil-image
    working_directory: /semantic-tests
    steps:
      - checkout
      - run:
          name: Execute tests
          command: |
            cd ..
            ./plexil/test/TestExec-regression-test/run-tests
            ls

workflows:
  version: 2
  build:
    jobs:
      - build