version: 2.1

jobs:
  build:
    docker:
      - image: semantictests/semantictests:plexil-image
    steps:
      - run:
          name: Execute tests
          command: |
            cd plexil/test/TestExec-regression-test/
            ./run-tests

workflows:
  version: 2
  build:
    jobs:
      - build
