version: 2.1

jobs:
  build:
    docker:
      - image: semantictests/semantictests:plexil-image
    working_directory: /
    steps:
      - run:
          name: Copy folder to Docker container
          command: docker cp README.md plexil-image:/
      - run:
          name: Execute tests
          command: |
            ./plexil/test/TestExec-regression-test/run-tests

workflows:
  version: 2
  build:
    jobs:
      - build
