version: 2.1

jobs:
  build:
    docker:
      - image: semantictests/semantictests:plexil-image
    steps:
      - setup_remote_docker:
          version: 20.10.8
      - checkout
      - run:
          name: Run Docker container
          command: |
            docker run -d --name plexil-container plexil-image
      - run:
          name: Execute tests
          command: |
            ./plexil/test/TestExec-regression-test/run-tests

workflows:
  version: 2
  build:
    jobs:
      - build
